In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from statsmodels.formula.api import ols

In [23]:
df_house = pd.read_csv('kc_house_data.csv')

In [43]:
df_house

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [24]:
df_house.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [38]:
# Define the problem
outcome = 'Price'

x_cols = ['id', 'date', 'bedrooms', 'bathrooms', 'sqft_living',
          'sqft_lot', 'floors', 'waterfront', 'view', 'condition',
          'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated',
          'zipcode','lat', 'long', 'sqft_living15', 'sqft_lot15']

In [39]:
predictors = '+'.join(x_cols)
predictors

'id+date+bedrooms+bathrooms+sqft_living+sqft_lot+floors+waterfront+view+condition+grade+sqft_above+sqft_basement+yr_built+yr_renovated+zipcode+lat+long+sqft_living15+sqft_lot15'

In [41]:
# Fitting the actual model
formula = outcome + '~' + predictors

In [42]:
model = ols(formula=formula, data=df_house).fit()
model.summary()

PatsyError: Error evaluating factor: NameError: name 'Price' is not defined
    Price~id+date+bedrooms+bathrooms+sqft_living+sqft_lot+floors+waterfront+view+condition+grade+sqft_above+sqft_basement+yr_built+yr_renovated+zipcode+lat+long+sqft_living15+sqft_lot15
    ^^^^^

In [8]:
# import df with outliers from price and bedrooms removed 
house_clean = pd.read_csv('housing_outliers_removed.csv')

In [9]:
#Checking for Colinarity 
co_lin = house_clean.corr().abs().stack().reset_index().sort_values(0, ascending=False)

co_lin['pairs'] = list(zip(co_lin.level_0, co_lin.level_1))

co_lin.set_index(['pairs'], inplace = True)

co_lin.drop(columns=['level_1', 'level_0'], inplace = True)

# cc for correlation coefficient
co_lin.columns = ['cc']

co_lin.drop_duplicates(inplace=True)

co_lin[(co_lin.cc>.7) & (co_lin.cc<1)]

                                    cc
pairs
(sqft_above, sqft_living)     0.857731
(sqft_living, sqft_living15)  0.744942
(sqft_living, bathrooms)      0.723443
(sqft_above, sqft_living15)   0.722329
(sqft_above, grade)           0.720057
(grade, sqft_living)          0.719541
(sqft_lot15, sqft_lot)        0.710867

In [ ]:
#droping unneeded columns